-- Insert El Cafetal restaurant for Galápagos Islands
-- Coordinates: -0.954514, -90.965874
-- Address: Casa Rosada, Puerto Villamil, Ecuador

INSERT INTO restaurants (
  destination_id,
  google_place_id,
  slug,
  name,
  short_name,
  description,
  summary,
  tagline,
  hero_image_url,
  image_alt,
  address,
  formatted_address,
  phone,
  formatted_phone,
  email,
  website,
  google_maps_url,
  neighborhood,
  latitude,
  longitude,
  google_rating,
  review_count,
  rating_source,
  cuisines,
  price_level,
  price_range,
  price_range_label,
  opening_hours,
  menu_highlights,
  highlights,
  review_summary,
  story,
  seo_title,
  seo_description,
  seo_keywords,
  booking_partner,
  booking_note,
  booking_url,
  booking_is_active,
  sustainability,
  practical_info,
  schema_data,
  google_data,
  address_components,
  plus_code,
  viewport,
  business_status,
  primary_type,
  serves_beer,
  serves_wine,
  serves_brunch,
  serves_dinner,
  utc_offset_minutes,
  adr_format_address,
  google_maps_uri,
  reviews_uri,
  photos_uri,
  next_open_time,
  open_now,
  unique_content,
  meta_description,
  is_active,
  is_featured,
  outdoor_seating,
  live_music,
  menu_for_children,
  serves_cocktails,
  serves_dessert,
  serves_coffee,
  good_for_children,
  allows_dogs,
  restroom,
  good_for_groups,
  reservable,
  dine_in,
  takeout,
  delivery,
  payment_options,
  parking_options,
  accessibility_options,
  reviews
) VALUES (
  'galapagos-islands',
  'MANUAL_ENTRY_el_cafetal_galapagos', -- Placeholder since Google Place ID is disabled
  'el-cafetal-galapagos-islands',
  'El Cafetal',
  'El Cafetal',
  '',
  '',
  '',
  NULL, -- Hero image URL (can be added later)
  'El Cafetal in Galápagos Islands',
  'Casa Rosada, Puerto Villamil, Ecuador',
  'Casa Rosada, Puerto Villamil, Ecuador',
  '+593 98 658 6209',
  '+593 98 658 6209',
  NULL,
  'https://instagram.com/elcafetal_galapagos',
  'https://maps.google.com/?q=-0.954514,-90.965874',
  'Puerto Villamil',
  '-0.954514',
  '-90.965874',
  4.40,
  136,
  'Google Reviews',
  ARRAY['Restaurant', 'Seafood', 'Cocktails', 'Vegetarian Friendly'],
  NULL,
  '$$',
  'Moderate',
  '[{"days": "Monday", "time": "10:00 AM – 10:00 PM", "label": "Monday"}, {"days": "Tuesday", "time": "10:00 AM – 10:00 PM", "label": "Tuesday"}, {"days": "Wednesday", "time": "10:00 AM – 10:00 PM", "label": "Wednesday"}, {"days": "Thursday", "time": "10:00 AM – 10:00 PM", "label": "Thursday"}, {"days": "Friday", "time": "10:00 AM – 10:00 PM", "label": "Friday"}, {"days": "Saturday", "time": "10:00 AM – 10:00 PM", "label": "Saturday"}, {"days": "Sunday", "time": "10:00 AM – 10:00 PM", "label": "Sunday"}]',
  NULL,
  NULL,
  'Beachfront spot on Isabela Island with friendly service, standout cocktails, and surprisingly broad vegetarian options. Lobster and seafood plates earn praise, with fair prices for a remote island. Located in a stunning seaside location next to Iguana Pink, offering ocean views and a refreshing sea breeze.',
  NULL,
  'El Cafetal | Beachfront Dining in Galápagos Islands',
  'Beachfront restaurant in Puerto Villamil with seafood, cocktails, and vegetarian options. Loved for friendly service, fair prices, and ocean views on Isabela Island, Galápagos.',
  ARRAY['El Cafetal Galápagos', 'Puerto Villamil restaurants', 'Isabela Island dining', 'seafood Galápagos', 'cocktails Galápagos', 'vegetarian restaurants Galápagos'],
  NULL,
  NULL,
  NULL,
  FALSE,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'OPERATIONAL',
  'Restaurant',
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  -360,
  'Puerto Villamil, Ecuador',
  'https://maps.google.com/?q=-0.954514,-90.965874',
  NULL,
  NULL,
  NULL,
  NULL,
  'Set on the sand in Puerto Villamil, El Cafetal pairs ocean views with friendly service, great cocktails, and fresh seafood. Vegetarian travelers call out the surprising variety, while locals love the generous portions and fair prices. It''s a relaxed, beachfront stop for lunch sunsets or easygoing dinners after a day of wildlife encounters. The restaurant''s new seaside location next to Iguana Pink offers an unforgettable dining experience with ocean views and a refreshing sea breeze.',
  'El Cafetal in Puerto Villamil blends ocean views, seafood, cocktails, and strong vegetarian options—friendly service and fair prices on Isabela Island, Galápagos.',
  TRUE,
  FALSE,
  TRUE,
  NULL,
  NULL,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  NULL,
  '{"acceptsNfc": true, "acceptsCashOnly": false, "acceptsDebitCards": true, "acceptsCreditCards": true}',
  NULL,
  NULL,
  NULL
);

